FROM rocker/shiny:3.6.3

RUN apt-get update -qq && apt-get autoclean \
 && apt-get autoremove && apt-get -y --no-install-recommends install \
  libxml2-dev \
  libcairo2-dev \
  libsqlite3-dev \
  libmariadbd-dev \
  libmariadbclient-dev \
  libpq-dev \
  libssl-dev \
  libcurl4-openssl-dev \
  libssh2-1-dev \
  unixodbc-dev \
  postgresql \
  postgresql-contrib \
  && install2.r --error \
    --deps TRUE \
    tidyverse \
    dplyr \
    devtools \
    formatR \
    remotes \
    selectr \
    caTools \
    BiocManager \
    DBI \
	RPostgreSQL \
  && rm -rf /tmp/downloaded_packages
  